// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'entities.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_LeadEntity _$LeadEntityFromJson(Map<String, dynamic> json) => _LeadEntity(
      guid: json['GUID'] as String?,
      id: (json['ID'] as num?)?.toInt(),
      partyId: (json['PARTY_ID'] as num?)?.toInt(),
      orgaName: json['ORGA_NAME'] as String?,
      type: (json['TYPE'] as num?)?.toInt(),
      typeName: json['TYPE_NAME'] as String?,
      companyName: json['COMPANY_NAME'] as String?,
      firstName: json['FIRST_NAME'],
      lastName: json['LAST_NAME'],
      integrationValue: json['INTEGRATION_VALUE'],
      name: json['NAME'] as String?,
      status: (json['STATUS'] as num?)?.toInt(),
      statusName: json['STATUS_NAME'] as String?,
      leadSource: (json['LEAD_SOURCE'] as num?)?.toInt(),
      leadSourceName: json['LEAD_SOURCE_NAME'] as String?,
      salesRepId: (json['SALES_REP_ID'] as num?)?.toInt(),
      salesRepName: json['SALES_REP_NAME'] as String?,
      territoryId: json['TERRITORY_ID'],
      territoryName: json['TERRITORY_NAME'],
      employeeId: json['EMPLOYEE_ID'],
      employeeName: json['EMPLOYEE_NAME'],
      qualifiedOn: json['QUALIFIED_ON'] == null
          ? null
          : DateTime.parse(json['QUALIFIED_ON'] as String),
      annualRevenue: json['ANNUAL_REVENUE'],
      noOfEmployee: json['NO_OF_EMPLOYEE'],
      industry: json['INDUSTRY'],
      latitude: json['LATITUDE'],
      longitude: json['LONGITUDE'],
      ledgerName: json['LEDGER_NAME'],
      visitNumber: json['VISIT_NUMBER'],
      personTitle: json['PERSON_TITLE'],
      orderPriority: json['ORDER_PRIORITY'],
      proprietorName: json['PROPRIETOR_NAME'],
      email: json['EMAIL'] as String?,
      phone: json['PHONE'] as String?,
      altPhone: json['ALT_PHONE'] as String?,
      fax: json['FAX'] as String?,
      address: json['ADDRESS'],
      shippingAddress: json['SHIPPING_ADDRESS'],
      address2: json['ADDRESS2'] as String?,
      segmentId: json['SEGMENT_ID'],
      customerCategoryId: json['CUSTOMER_CATEGORY_ID'],
      customerCategoryName: json['CUSTOMER_CATEGORY_NAME'],
      buyingIntensionId: json['BUYING_INTENSION_ID'],
      vehicleId: json['VEHICLE_ID'],
      panNo: json['PAN_NO'],
      isIndividual: json['IS_INDIVIDUAL'] as bool?,
      isVisit: json['IS_VISIT'] as bool?,
      visitDate: json['VISIT_DATE'] == null
          ? null
          : DateTime.parse(json['VISIT_DATE'] as String),
      isPottential: json['IS_POTTENTIAL'] as bool?,
      pottentialDate: json['POTTENTIAL_DATE'],
      isBilled: json['IS_BILLED'] as bool?,
      isBilledSync: json['IS_BILLED_SYNC'] as bool?,
      billedDate: json['BILLED_DATE'] == null
          ? null
          : DateTime.parse(json['BILLED_DATE'] as String),
      reasonForCloseLost: json['REASON_FOR_CLOSE_LOST'],
      subsidiaryId: json['SUBSIDIARY_ID'],
      subsidiaryName: json['SUBSIDIARY_NAME'],
      memo: json['MEMO'],
      isUpdated: json['IS_UPDATED'] as bool?,
      isBanned: json['IS_BANNED'] as bool?,
      isInactive: json['IS_INACTIVE'] as bool?,
      prospectStatus: json['PROSPECT_STATUS'],
      prospectStatusName: json['PROSPECT_STATUS_NAME'] as String?,
      prospectSource: json['PROSPECT_SOURCE'],
      prospectSourceName: json['PROSPECT_SOURCE_NAME'],
      webAddress: json['WEB_ADDRESS'],
      classId: json['CLASS_ID'],
      className: json['class_name'],
      currencyId: json['CURRENCY_ID'],
      currencyName: json['CURRENCY_NAME'],
      termId: json['TERM_ID'],
      termName: json['TERM_NAME'],
      whTaxId: json['WH_TAX_ID'],
      whTaxCode: json['WH_TAX_CODE'],
      taxId: json['TAX_ID'],
      taxCode: json['TAX_CODE'],
      creditLimit: json['CREDIT_LIMIT'],
      holdStatus: (json['HOLD_STATUS'] as num?)?.toInt(),
      holdStatusName: json['HOLD_STATUS_NAME'] as String?,
    );

Map<String, dynamic> _$LeadEntityToJson(_LeadEntity instance) =>
    <String, dynamic>{
      if (instance.guid case final value?) 'GUID': value,
      if (instance.id case final value?) 'ID': value,
      if (instance.partyId case final value?) 'PARTY_ID': value,
      if (instance.orgaName case final value?) 'ORGA_NAME': value,
      if (instance.type case final value?) 'TYPE': value,
      if (instance.typeName case final value?) 'TYPE_NAME': value,
      if (instance.companyName case final value?) 'COMPANY_NAME': value,
      if (instance.firstName case final value?) 'FIRST_NAME': value,
      if (instance.lastName case final value?) 'LAST_NAME': value,
      if (instance.integrationValue case final value?)
        'INTEGRATION_VALUE': value,
      if (instance.name case final value?) 'NAME': value,
      if (instance.status case final value?) 'STATUS': value,
      if (instance.statusName case final value?) 'STATUS_NAME': value,
      if (instance.leadSource case final value?) 'LEAD_SOURCE': value,
      if (instance.leadSourceName case final value?) 'LEAD_SOURCE_NAME': value,
      if (instance.salesRepId case final value?) 'SALES_REP_ID': value,
      if (instance.salesRepName case final value?) 'SALES_REP_NAME': value,
      if (instance.territoryId case final value?) 'TERRITORY_ID': value,
      if (instance.territoryName case final value?) 'TERRITORY_NAME': value,
      if (instance.employeeId case final value?) 'EMPLOYEE_ID': value,
      if (instance.employeeName case final value?) 'EMPLOYEE_NAME': value,
      if (instance.qualifiedOn?.toIso8601String() case final value?)
        'QUALIFIED_ON': value,
      if (instance.annualRevenue case final value?) 'ANNUAL_REVENUE': value,
      if (instance.noOfEmployee case final value?) 'NO_OF_EMPLOYEE': value,
      if (instance.industry case final value?) 'INDUSTRY': value,
      if (instance.latitude case final value?) 'LATITUDE': value,
      if (instance.longitude case final value?) 'LONGITUDE': value,
      if (instance.ledgerName case final value?) 'LEDGER_NAME': value,
      if (instance.visitNumber case final value?) 'VISIT_NUMBER': value,
      if (instance.personTitle case final value?) 'PERSON_TITLE': value,
      if (instance.orderPriority case final value?) 'ORDER_PRIORITY': value,
      if (instance.proprietorName case final value?) 'PROPRIETOR_NAME': value,
      if (instance.email case final value?) 'EMAIL': value,
      if (instance.phone case final value?) 'PHONE': value,
      if (instance.altPhone case final value?) 'ALT_PHONE': value,
      if (instance.fax case final value?) 'FAX': value,
      if (instance.address case final value?) 'ADDRESS': value,
      if (instance.shippingAddress case final value?) 'SHIPPING_ADDRESS': value,
      if (instance.address2 case final value?) 'ADDRESS2': value,
      if (instance.segmentId case final value?) 'SEGMENT_ID': value,
      if (instance.customerCategoryId case final value?)
        'CUSTOMER_CATEGORY_ID': value,
      if (instance.customerCategoryName case final value?)
        'CUSTOMER_CATEGORY_NAME': value,
      if (instance.buyingIntensionId case final value?)
        'BUYING_INTENSION_ID': value,
      if (instance.vehicleId case final value?) 'VEHICLE_ID': value,
      if (instance.panNo case final value?) 'PAN_NO': value,
      if (instance.isIndividual case final value?) 'IS_INDIVIDUAL': value,
      if (instance.isVisit case final value?) 'IS_VISIT': value,
      if (instance.visitDate?.toIso8601String() case final value?)
        'VISIT_DATE': value,
      if (instance.isPottential case final value?) 'IS_POTTENTIAL': value,
      if (instance.pottentialDate case final value?) 'POTTENTIAL_DATE': value,
      if (instance.isBilled case final value?) 'IS_BILLED': value,
      if (instance.isBilledSync case final value?) 'IS_BILLED_SYNC': value,
      if (instance.billedDate?.toIso8601String() case final value?)
        'BILLED_DATE': value,
      if (instance.reasonForCloseLost case final value?)
        'REASON_FOR_CLOSE_LOST': value,
      if (instance.subsidiaryId case final value?) 'SUBSIDIARY_ID': value,
      if (instance.subsidiaryName case final value?) 'SUBSIDIARY_NAME': value,
      if (instance.memo case final value?) 'MEMO': value,
      if (instance.isUpdated case final value?) 'IS_UPDATED': value,
      if (instance.isBanned case final value?) 'IS_BANNED': value,
      if (instance.isInactive case final value?) 'IS_INACTIVE': value,
      if (instance.prospectStatus case final value?) 'PROSPECT_STATUS': value,
      if (instance.prospectStatusName case final value?)
        'PROSPECT_STATUS_NAME': value,
      if (instance.prospectSource case final value?) 'PROSPECT_SOURCE': value,
      if (instance.prospectSourceName case final value?)
        'PROSPECT_SOURCE_NAME': value,
      if (instance.webAddress case final value?) 'WEB_ADDRESS': value,
      if (instance.classId case final value?) 'CLASS_ID': value,
      if (instance.className case final value?) 'class_name': value,
      if (instance.currencyId case final value?) 'CURRENCY_ID': value,
      if (instance.currencyName case final value?) 'CURRENCY_NAME': value,
      if (instance.termId case final value?) 'TERM_ID': value,
      if (instance.termName case final value?) 'TERM_NAME': value,
      if (instance.whTaxId case final value?) 'WH_TAX_ID': value,
      if (instance.whTaxCode case final value?) 'WH_TAX_CODE': value,
      if (instance.taxId case final value?) 'TAX_ID': value,
      if (instance.taxCode case final value?) 'TAX_CODE': value,
      if (instance.creditLimit case final value?) 'CREDIT_LIMIT': value,
      if (instance.holdStatus case final value?) 'HOLD_STATUS': value,
      if (instance.holdStatusName case final value?) 'HOLD_STATUS_NAME': value,
    };

_LeadParam _$LeadParamFromJson(Map<String, dynamic> json) => _LeadParam(
      visitId: (json['visit_id'] as num?)?.toInt() ?? 0,
      organisationId: (json['organisation_id'] as num?)?.toInt(),
      leadStatus: (json['lead_status'] as num?)?.toInt() ?? 1,
      type: (json['type'] as num?)?.toInt(),
      isIndividual: json['is_individual'] as bool?,
      companyName: json['company_name'] as String?,
      leadSource: (json['lead_source'] as num?)?.toInt(),
      isVisitNoAuto: json['is_visit_no_auto'] as bool?,
      firstName: json['first_name'] as String?,
      lastName: json['last_name'] as String?,
      personTitle: json['person_title'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      altPhone: json['alt_phone'] as String?,
      fax: json['fax'] as String?,
      address2: json['address2'] as String?,
      isBanned: json['is_banned'] as bool?,
      isInactive: json['is_inactive'] as bool?,
      customerCategoryId: json['customer_category_id'],
      isVisit: json['is_visit'] as bool?,
      ledgerId: json['ledger_id'],
      salesRepId: (json['sales_rep_id'] as num?)?.toInt(),
      territoryId: json['territory_id'],
      employeeId: json['employee_id'],
      qualifiedOn: json['qualified_on'],
      annualRevenue: json['annual_revenue'],
      noOfEmployee: json['no_of_employee'],
      industry: json['industry'],
      address: json['address'],
      shippingAddress: json['shipping_address'],
      webAddress: json['web_address'],
      messageList: json['message_list'] as List<dynamic>?,
      taskList: json['task_list'] as List<dynamic>?,
      eventList: json['event_list'] as List<dynamic>?,
      phoneCallDetails: json['phone_call_details'] as List<dynamic>?,
      userNoteDetails: json['user_note_details'] as List<dynamic>?,
      relationshipDetails: json['relationship_details'] as List<dynamic>?,
      fileList: json['fileList'] as List<dynamic>?,
    );

Map<String, dynamic> _$LeadParamToJson(_LeadParam instance) =>
    <String, dynamic>{
      'visit_id': instance.visitId,
      if (instance.organisationId case final value?) 'organisation_id': value,
      if (instance.leadStatus case final value?) 'lead_status': value,
      if (instance.type case final value?) 'type': value,
      if (instance.isIndividual case final value?) 'is_individual': value,
      if (instance.companyName case final value?) 'company_name': value,
      if (instance.leadSource case final value?) 'lead_source': value,
      if (instance.isVisitNoAuto case final value?) 'is_visit_no_auto': value,
      if (instance.firstName case final value?) 'first_name': value,
      if (instance.lastName case final value?) 'last_name': value,
      if (instance.personTitle case final value?) 'person_title': value,
      if (instance.email case final value?) 'email': value,
      if (instance.phone case final value?) 'phone': value,
      if (instance.altPhone case final value?) 'alt_phone': value,
      if (instance.fax case final value?) 'fax': value,
      if (instance.address2 case final value?) 'address2': value,
      if (instance.isBanned case final value?) 'is_banned': value,
      if (instance.isInactive case final value?) 'is_inactive': value,
      if (instance.customerCategoryId case final value?)
        'customer_category_id': value,
      if (instance.isVisit case final value?) 'is_visit': value,
      if (instance.ledgerId case final value?) 'ledger_id': value,
      if (instance.salesRepId case final value?) 'sales_rep_id': value,
      if (instance.territoryId case final value?) 'territory_id': value,
      if (instance.employeeId case final value?) 'employee_id': value,
      if (instance.qualifiedOn case final value?) 'qualified_on': value,
      if (instance.annualRevenue case final value?) 'annual_revenue': value,
      if (instance.noOfEmployee case final value?) 'no_of_employee': value,
      if (instance.industry case final value?) 'industry': value,
      if (instance.address case final value?) 'address': value,
      if (instance.shippingAddress case final value?) 'shipping_address': value,
      if (instance.webAddress case final value?) 'web_address': value,
      if (instance.messageList case final value?) 'message_list': value,
      if (instance.taskList case final value?) 'task_list': value,
      if (instance.eventList case final value?) 'event_list': value,
      if (instance.phoneCallDetails case final value?)
        'phone_call_details': value,
      if (instance.userNoteDetails case final value?)
        'user_note_details': value,
      if (instance.relationshipDetails case final value?)
        'relationship_details': value,
      if (instance.fileList case final value?) 'fileList': value,
    };
