part of 'entities.dart';

@freezed
abstract class LeadEntity with _$LeadEntity {
  const factory LeadEntity({
    @JsonKey(name: "GUID") String? guid,
    @JsonKey(name: "ID") int? id,
    @JsonKey(name: "PARTY_ID") int? partyId,
    @JsonKey(name: "ORGA_NAME") String? orgaName,
    @JsonKey(name: "TYPE") int? type,
    @JsonKey(name: "TYPE_NAME") String? typeName,
    @JsonKey(name: "COMPANY_NAME") String? companyName,
    @JsonKey(name: "FIRST_NAME") dynamic firstName,
    @JsonKey(name: "LAST_NAME") dynamic lastName,
    @JsonKey(name: "INTEGRATION_VALUE") dynamic integrationValue,
    @JsonKey(name: "NAME") String? name,
    @JsonKey(name: "STATUS") int? status,
    @JsonKey(name: "STATUS_NAME") String? statusName,
    @JsonKey(name: "LEAD_SOURCE") int? leadSource,
    @JsonKey(name: "LEAD_SOURCE_NAME") String? leadSourceName,
    @JsonKey(name: "SALES_REP_ID") int? salesRepId,
    @JsonKey(name: "SALES_REP_NAME") String? salesRepName,
    @JsonKey(name: "TERRITORY_ID") dynamic territoryId,
    @JsonKey(name: "TERRITORY_NAME") dynamic territoryName,
    @JsonKey(name: "EMPLOYEE_ID") dynamic employeeId,
    @JsonKey(name: "EMPLOYEE_NAME") dynamic employeeName,
    @JsonKey(name: "QUALIFIED_ON") DateTime? qualifiedOn,
    @JsonKey(name: "ANNUAL_REVENUE") dynamic annualRevenue,
    @JsonKey(name: "NO_OF_EMPLOYEE") dynamic noOfEmployee,
    @JsonKey(name: "INDUSTRY") dynamic industry,
    @JsonKey(name: "LATITUDE") dynamic latitude,
    @JsonKey(name: "LONGITUDE") dynamic longitude,
    @JsonKey(name: "LEDGER_NAME") dynamic ledgerName,
    @JsonKey(name: "VISIT_NUMBER") dynamic visitNumber,
    @JsonKey(name: "PERSON_TITLE") dynamic personTitle,
    @JsonKey(name: "ORDER_PRIORITY") dynamic orderPriority,
    @JsonKey(name: "PROPRIETOR_NAME") dynamic proprietorName,
    @JsonKey(name: "EMAIL") String? email,
    @JsonKey(name: "PHONE") String? phone,
    @JsonKey(name: "ALT_PHONE") String? altPhone,
    @JsonKey(name: "FAX") String? fax,
    @JsonKey(name: "ADDRESS") dynamic address,
    @JsonKey(name: "SHIPPING_ADDRESS") dynamic shippingAddress,
    @JsonKey(name: "ADDRESS2") String? address2,
    @JsonKey(name: "SEGMENT_ID") dynamic segmentId,
    @JsonKey(name: "CUSTOMER_CATEGORY_ID") dynamic customerCategoryId,
    @JsonKey(name: "CUSTOMER_CATEGORY_NAME") dynamic customerCategoryName,
    @JsonKey(name: "BUYING_INTENSION_ID") dynamic buyingIntensionId,
    @JsonKey(name: "VEHICLE_ID") dynamic vehicleId,
    @JsonKey(name: "PAN_NO") dynamic panNo,
    @JsonKey(name: "IS_INDIVIDUAL") bool? isIndividual,
    @JsonKey(name: "IS_VISIT") bool? isVisit,
    @JsonKey(name: "VISIT_DATE") DateTime? visitDate,
    @JsonKey(name: "IS_POTTENTIAL") bool? isPottential,
    @JsonKey(name: "POTTENTIAL_DATE") dynamic pottentialDate,
    @JsonKey(name: "IS_BILLED") bool? isBilled,
    @JsonKey(name: "IS_BILLED_SYNC") bool? isBilledSync,
    @JsonKey(name: "BILLED_DATE") DateTime? billedDate,
    @JsonKey(name: "REASON_FOR_CLOSE_LOST") dynamic reasonForCloseLost,
    @JsonKey(name: "SUBSIDIARY_ID") dynamic subsidiaryId,
    @JsonKey(name: "SUBSIDIARY_NAME") dynamic subsidiaryName,
    @JsonKey(name: "MEMO") dynamic memo,
    @JsonKey(name: "IS_UPDATED") bool? isUpdated,
    @JsonKey(name: "IS_BANNED") bool? isBanned,
    @JsonKey(name: "IS_INACTIVE") bool? isInactive,
    @JsonKey(name: "PROSPECT_STATUS") dynamic prospectStatus,
    @JsonKey(name: "PROSPECT_STATUS_NAME") String? prospectStatusName,
    @JsonKey(name: "PROSPECT_SOURCE") dynamic prospectSource,
    @JsonKey(name: "PROSPECT_SOURCE_NAME") dynamic prospectSourceName,
    @JsonKey(name: "WEB_ADDRESS") dynamic webAddress,
    @JsonKey(name: "CLASS_ID") dynamic classId,
    @JsonKey(name: "class_name") dynamic className,
    @JsonKey(name: "CURRENCY_ID") dynamic currencyId,
    @JsonKey(name: "CURRENCY_NAME") dynamic currencyName,
    @JsonKey(name: "TERM_ID") dynamic termId,
    @JsonKey(name: "TERM_NAME") dynamic termName,
    @JsonKey(name: "WH_TAX_ID") dynamic whTaxId,
    @JsonKey(name: "WH_TAX_CODE") dynamic whTaxCode,
    @JsonKey(name: "TAX_ID") dynamic taxId,
    @JsonKey(name: "TAX_CODE") dynamic taxCode,
    @JsonKey(name: "CREDIT_LIMIT") dynamic creditLimit,
    @JsonKey(name: "HOLD_STATUS") int? holdStatus,
    @JsonKey(name: "HOLD_STATUS_NAME") String? holdStatusName,
  }) = _LeadEntity;

  factory LeadEntity.fromJson(Map<String, dynamic> json) =>
      _$LeadEntityFromJson(json);
}
