part of 'entities.dart';

@freezed
abstract class CustomerEntity with _$CustomerEntity {
  const factory CustomerEntity({
    @JsonKey(name: "id") int? id,
    @JsonKey(name: "visit_id") int? visitId,
    @JsonKey(name: "visit_number") String? visitNumber,
    @JsonKey(name: "code") String? code,
    @JsonKey(name: "full_name") String? fullName,
    @JsonKey(name: "person_title") String? personTitle,
    @JsonKey(name: "order_priority") dynamic orderPriority,
    @JsonKey(name: "type") int? type,
    @JsonKey(name: "first_name") String? firstName,
    @JsonKey(name: "last_name") String? lastName,
    @JsonKey(name: "company_name") String? companyName,
    @JsonKey(name: "address1") String? address1,
    @JsonKey(name: "contact") String? contact,
    @JsonKey(name: "memo") String? memo,
    @JsonKey(name: "citizenship_no") String? citizenshipNo,
    @JsonKey(name: "proprietor_name") String? proprietorName,
    @JsonKey(name: "email") String? email,
    @JsonKey(name: "phone") String? phone,
    @JsonKey(name: "alt_phone") String? altPhone,
    @JsonKey(name: "fax") String? fax,
    @JsonKey(name: "address") String? address,
    @JsonKey(name: "shipping_address") String? shippingAddress,
    @JsonKey(name: "address2") String? address2,
    @JsonKey(name: "is_individual") bool? isIndividual,
    @JsonKey(name: "is_banned") bool? isBanned,
    @JsonKey(name: "is_inactive") bool? isInactive,
    @JsonKey(name: "location_id") int? locationId,
    @JsonKey(name: "subsidiary_id") int? subsidiaryId,
    @JsonKey(name: "customer_category_id") int? customerCategoryId,
    @JsonKey(name: "status") int? status,
    @JsonKey(name: "prospect_status") int? prospectStatus,
    @JsonKey(name: "customer_status") int? customerStatus,
    @JsonKey(name: "lead_source") dynamic leadSource,
    @JsonKey(name: "prospect_source") dynamic prospectSource,
    @JsonKey(name: "employee_id") int? employeeId,
    @JsonKey(name: "qualified_on") DateTime? qualifiedOn,
    @JsonKey(name: "annual_revenue") dynamic annualRevenue,
    @JsonKey(name: "no_of_employee") dynamic noOfEmployee,
    @JsonKey(name: "industry") dynamic industry,
    @JsonKey(name: "web_address") dynamic webAddress,
    @JsonKey(name: "class_id") dynamic classId,
    @JsonKey(name: "currency_id") int? currencyId,
    @JsonKey(name: "term_id") dynamic termId,
    @JsonKey(name: "ledger_id") int? ledgerId,
    @JsonKey(name: "pan_no") String? panNo,
    @JsonKey(name: "pan") String? pan,
    @JsonKey(name: "reason_for_close_lost") dynamic reasonForCloseLost,
    @JsonKey(name: "is_visit") bool? isVisit,
    @JsonKey(name: "visit_date") dynamic visitDate,
    @JsonKey(name: "is_visit_sync") bool? isVisitSync,
    @JsonKey(name: "is_potential") bool? isPotential,
    @JsonKey(name: "potential_date") dynamic potentialDate,
    @JsonKey(name: "is_potential_sync") bool? isPotentialSync,
    @JsonKey(name: "is_billed") bool? isBilled,
    @JsonKey(name: "sales_rep_id") int? salesRepId,
    @JsonKey(name: "wh_tax_id") dynamic whTaxId,
    @JsonKey(name: "tax_id") dynamic taxId,
    @JsonKey(name: "credit_limit") dynamic creditLimit,
    @JsonKey(name: "hold_status") int? holdStatus,
    @JsonKey(name: "source_website") dynamic sourceWebsite,
    @JsonKey(name: "campaign") dynamic campaign,
    @JsonKey(name: "billed_date") DateTime? billedDate,
    @JsonKey(name: "is_billed_sync") bool? isBilledSync,
    @JsonKey(name: "is_updated") bool? isUpdated,
    @JsonKey(name: "is_cancelled") bool? isCancelled,
    @JsonKey(name: "territory_id") dynamic territoryId,
    @JsonKey(name: "segment_id") dynamic segmentId,
    @JsonKey(name: "application_id") dynamic applicationId,
    @JsonKey(name: "vehicle_id") dynamic vehicleId,
    @JsonKey(name: "buying_intention_id") dynamic buyingIntentionId,
    @JsonKey(name: "area_id") dynamic areaId,
    @JsonKey(name: "tole") dynamic tole,
    @JsonKey(name: "ward_no") dynamic wardNo,
    @JsonKey(name: "date_of_birth") dynamic dateOfBirth,
    @JsonKey(name: "dob_bs") dynamic dobBs,
    @JsonKey(name: "issue_date") dynamic issueDate,
    @JsonKey(name: "expiry_date") dynamic expiryDate,
    @JsonKey(name: "balance") dynamic balance,
    @JsonKey(name: "gender") dynamic gender,
    @JsonKey(name: "is_member") bool? isMember,
    @JsonKey(name: "partner_id") dynamic partnerId,
    @JsonKey(name: "party_record_type") int? partyRecordType,
    @JsonKey(name: "image_path") dynamic imagePath,
    @JsonKey(name: "age") dynamic age,
    @JsonKey(name: "insurance_no") dynamic insuranceNo,
    @JsonKey(name: "latitude") double? latitude,
    @JsonKey(name: "longitude") double? longitude,
    @JsonKey(name: "sub_type") dynamic subType,
    @JsonKey(name: "is_default") bool? isDefault,
  }) = _CustomerEntity;

  factory CustomerEntity.fromJson(Map<String, dynamic> json) =>
      _$CustomerEntityFromJson(json);
}
