part of 'entities.dart';

@freezed
abstract class ItemEntity with _$ItemEntity {
  const factory ItemEntity({
    @JsonKey(name: "performed_by") int? performedBy,
    @JsonKey(name: "item_id") int? itemId,
    @JsonKey(name: "standard_unit_id") int? standardUnitId,
    @JsonKey(name: "is_maintain_stock") bool? isMaintainStock,
    @JsonKey(name: "is_multiple_uom") bool? isMultipleUom,
    @JsonKey(name: "is_variant") bool? isVariant,
    @JsonKey(name: "is_fixed_assets") bool? isFixedAssets,
    @JsonKey(name: "purchase_unit_id") int? purchaseUnitId,
    @JsonKey(name: "sales_unit_id") int? salesUnitId,
    @JsonKey(name: "stock_unit_id") int? stockUnitId,
    @JsonKey(name: "consumption_out_unit_id") int? consumptionOutUnitId,
    @JsonKey(name: "category_id") int? categoryId,
    @JsonKey(name: "brand_id") int? brandId,
    @JsonKey(name: "initial_purchase_rate") double? initialPurchaseRate,
    @JsonKey(name: "initial_sales_rate") double? initialSalesRate,
    @JsonKey(name: "item_type") int? itemType,
    @JsonKey(name: "sub_type") dynamic subType,
    @JsonKey(name: "is_track_landed_cost") bool? isTrackLandedCost,
    @JsonKey(name: "item_description") String? itemDescription,
    @JsonKey(name: "is_inactive") bool? isInactive,
    @JsonKey(name: "income_account_id") int? incomeAccountId,
    @JsonKey(name: "expense_account_id") int? expenseAccountId,
    @JsonKey(name: "asset_account_id") int? assetAccountId,
    @JsonKey(name: "cogs_account_id") int? cogsAccountId,
    @JsonKey(name: "gain_loss_account_id") int? gainLossAccountId,
    @JsonKey(name: "is_non_posting") bool? isNonPosting,
    @JsonKey(name: "life_in_days") dynamic lifeInDays,
    @JsonKey(name: "warranty_period") dynamic warrantyPeriod,
    @JsonKey(name: "end_of_life") dynamic endOfLife,
    @JsonKey(name: "costing_method") int? costingMethod,
    @JsonKey(name: "safety_stock_level") dynamic safetyStockLevel,
    @JsonKey(name: "reorder_minimun_quantity") dynamic reorderMinimunQuantity,
    @JsonKey(name: "is_serialized") bool? isSerialized,
    @JsonKey(name: "is_batch_no") bool? isBatchNo,
    @JsonKey(name: "is_allow_negetive_stock") bool? isAllowNegetiveStock,
    @JsonKey(name: "minimun_order_quantity") dynamic minimunOrderQuantity,
    @JsonKey(name: "lead_time_in_days") dynamic leadTimeInDays,
    @JsonKey(name: "vendor_id") dynamic vendorId,
    @JsonKey(name: "is_discount_allowed") bool? isDiscountAllowed,
    @JsonKey(name: "default_discount_amount") double? defaultDiscountAmount,
    @JsonKey(name: "default_discount_percentage")
    int? defaultDiscountPercentage,
    @JsonKey(name: "is_grant_comision") bool? isGrantComision,
    @JsonKey(name: "has_warranty") bool? hasWarranty,
    @JsonKey(name: "minimun_sales_quantity") dynamic minimunSalesQuantity,
    @JsonKey(name: "max_sales_quantity") dynamic maxSalesQuantity,
    @JsonKey(name: "tax_id") int? taxId,
    @JsonKey(name: "parent_id") dynamic parentId,
    @JsonKey(name: "item_code") String? itemCode,
    @JsonKey(name: "hs_code") String? hsCode,
    @JsonKey(name: "item_name") String? itemName,
    @JsonKey(name: "brand_name") dynamic brandName,
    @JsonKey(name: "short_cut") dynamic shortCut,
    @JsonKey(name: "quantity") int? quantity,
    @JsonKey(name: "wh_tax_code") dynamic whTaxCode,
    @JsonKey(name: "tax_schedule") dynamic taxSchedule,
    @JsonKey(name: "lot_no") dynamic lotNo,
    @JsonKey(name: "org_name") String? orgName,
    @JsonKey(name: "location_id") dynamic locationId,
    @JsonKey(name: "cost_estimate_type") int? costEstimateType,
    @JsonKey(name: "subsidiary_id") int? subsidiaryId,
    @JsonKey(name: "class_id") dynamic classId,
    @JsonKey(name: "department_id") dynamic departmentId,
    @JsonKey(name: "data_sheet_id") dynamic dataSheetId,
    @JsonKey(name: "purchase_description") dynamic purchaseDescription,
    @JsonKey(name: "transfer_price") dynamic transferPrice,
    @JsonKey(name: "manufacturer") dynamic manufacturer,
    @JsonKey(name: "mpn") dynamic mpn,
    @JsonKey(name: "manufacturer_country") dynamic manufacturerCountry,
    @JsonKey(name: "po_quantity_tolerance") dynamic poQuantityTolerance,
    @JsonKey(name: "po_amount_difference") dynamic poAmountDifference,
    @JsonKey(name: "po_quantity_difference") dynamic poQuantityDifference,
    @JsonKey(name: "item_receipt_quantity_tolerance")
    dynamic itemReceiptQuantityTolerance,
    @JsonKey(name: "item_receipt_amount_tolerance")
    dynamic itemReceiptAmountTolerance,
    @JsonKey(name: "item_receipt_quantity_difference")
    dynamic itemReceiptQuantityDifference,
    @JsonKey(name: "sales_description") dynamic salesDescription,
    @JsonKey(name: "maximum_order_quantity") dynamic maximumOrderQuantity,
    @JsonKey(name: "item_define_cost") dynamic itemDefineCost,
    @JsonKey(name: "item_weight") dynamic itemWeight,
    @JsonKey(name: "package_id") dynamic packageId,
    @JsonKey(name: "handling_cost") dynamic handlingCost,
    @JsonKey(name: "shipping_cost") dynamic shippingCost,
    @JsonKey(name: "cost_estimate") dynamic costEstimate,
    @JsonKey(name: "deffered_account_id") dynamic defferedAccountId,
    @JsonKey(name: "price_variance_account_id") dynamic priceVarianceAccountId,
    @JsonKey(name: "quantity_variance_account_id")
    dynamic quantityVarianceAccountId,
    @JsonKey(name: "apply_before_salestax") dynamic applyBeforeSalestax,
    @JsonKey(name: "deffered_expenses_account_id")
    dynamic defferedExpensesAccountId,
    @JsonKey(name: "exchange_rate_variance_account_id")
    dynamic exchangeRateVarianceAccountId,
    @JsonKey(name: "scrap_account_id") dynamic scrapAccountId,
    @JsonKey(name: "wip_account_id") dynamic wipAccountId,
    @JsonKey(name: "rate") double? rate,
    @JsonKey(name: "IsPercentage") bool? isPercentage,
    @JsonKey(name: "max_thresshold") int? maxThresshold,
    @JsonKey(name: "min_thresshold") int? minThresshold,
    @JsonKey(name: "tax_percentage") int? taxPercentage,
    @JsonKey(name: "is_taxable") bool? isTaxable,
    @JsonKey(name: "is_inclusive") bool? isInclusive,
    @JsonKey(name: "image_path") String? imagePath,
    @JsonKey(name: "type") dynamic type,
    @JsonKey(name: "address") String? address,
    @JsonKey(name: "remarks") String? remarks,
    @JsonKey(name: "manufacture_date") dynamic manufactureDate,
    @JsonKey(name: "expiry_date") dynamic expiryDate,
    @JsonKey(name: "serial_no") dynamic serialNo,
    @JsonKey(name: "custom_field") dynamic customField,
    @JsonKey(name: "StandardUnit") UnitEntity? standardUnit,
    @JsonKey(name: "PurchaseUnit") dynamic purchaseUnit,
    @JsonKey(name: "SalesUnit") dynamic salesUnit,
  }) = _ItemEntity;

  factory ItemEntity.fromJson(Map<String, dynamic> json) =>
      _$ItemEntityFromJson(json);
}
