part of 'entities.dart';

@freezed
abstract class CreditMemo with _$CreditMemo {
  const factory CreditMemo({
    int? id,
    int? customerId,
    String? docNo,
    String? creditMemoNo,
    String? customer,
    DateTime? creditMemoDate,
    String? nepCreditMemoDate,
    String? currencyName,
    String? departmentName,
    String? nextApproverName,
    int? refType,
    String? memo,
    String? locationName,
    int? status,
    int? approvalStatus,
    String? statusName,
    int? partyId,
    int? currencyId,
    int? exchangeRate,
    String? panNo,
    int? creditMemoId,
    String? invoiceReferenceNo,
    int? refInvoiceId,
    int? locationId,
    bool? isCancelled,
    int? salesRepId,
    int? ledgerId,
    dynamic credit,
    String? purpose,
    num? discount,
    num? discountAmount,
    num? grossAmount,
    num? taxableAmount,
    num? taxAmount,
    int? netTotal,
    num? netAmount,
    String? itemName,
    String? partyName,
    num? itemRate,
    bool? autoApply,
    @Default([]) List<CreditMemoDetail> details,
  }) = _CreditMemo;
}
